/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OsRouteRouteImport } from './routes/os/route'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as FilmsSlugRouteImport } from './routes/films/$slug'
import { Route as OsIndexRouteImport } from './routes/os/index'
import { Route as OsCalendarRouteImport } from './routes/os/calendar'
import { Route as OsCrewRouteImport } from './routes/os/crew'
import { Route as OsDashboardRouteImport } from './routes/os/dashboard'
import { Route as OsLoginRouteImport } from './routes/os/login'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as OsClientsIndexRouteImport } from './routes/os/clients/index'
import { Route as OsProductionsIndexRouteImport } from './routes/os/productions/index'
import { Route as OsProductionsIdRouteImport } from './routes/os/productions/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRouteRoute = OsRouteRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsCalendarRoute = OsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsCrewRoute = OsCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsDashboardRoute = OsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsLoginRoute = OsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OsRouteRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OsClientsIndexRoute = OsClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsProductionsIndexRoute = OsProductionsIndexRouteImport.update({
  id: '/productions/',
  path: '/productions/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsProductionsIdRoute = OsProductionsIdRouteImport.update({
  id: '/productions/$id',
  path: '/productions/$id',
  getParentRoute: () => OsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/os': typeof OsRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/studio': typeof StudioRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/crew': typeof OsCrewRoute
  '/os/dashboard': typeof OsDashboardRoute
  '/os/login': typeof OsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/os/': typeof OsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/os/productions/$id': typeof OsProductionsIdRoute
  '/os/clients/': typeof OsClientsIndexRoute
  '/os/productions/': typeof OsProductionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/studio': typeof StudioRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/crew': typeof OsCrewRoute
  '/os/dashboard': typeof OsDashboardRoute
  '/os/login': typeof OsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/os': typeof OsIndexRoute
  '/work': typeof WorkIndexRoute
  '/os/productions/$id': typeof OsProductionsIdRoute
  '/os/clients': typeof OsClientsIndexRoute
  '/os/productions': typeof OsProductionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/os': typeof OsRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/studio': typeof StudioRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/crew': typeof OsCrewRoute
  '/os/dashboard': typeof OsDashboardRoute
  '/os/login': typeof OsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/os/': typeof OsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/os/productions/$id': typeof OsProductionsIdRoute
  '/os/clients/': typeof OsClientsIndexRoute
  '/os/productions/': typeof OsProductionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/os'
    | '/contact'
    | '/studio'
    | '/films/$slug'
    | '/os/calendar'
    | '/os/crew'
    | '/os/dashboard'
    | '/os/login'
    | '/work/$slug'
    | '/os/'
    | '/work/'
    | '/os/productions/$id'
    | '/os/clients/'
    | '/os/productions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/studio'
    | '/films/$slug'
    | '/os/calendar'
    | '/os/crew'
    | '/os/dashboard'
    | '/os/login'
    | '/work/$slug'
    | '/os'
    | '/work'
    | '/os/productions/$id'
    | '/os/clients'
    | '/os/productions'
  id:
    | '__root__'
    | '/'
    | '/os'
    | '/contact'
    | '/studio'
    | '/films/$slug'
    | '/os/calendar'
    | '/os/crew'
    | '/os/dashboard'
    | '/os/login'
    | '/work/$slug'
    | '/os/'
    | '/work/'
    | '/os/productions/$id'
    | '/os/clients/'
    | '/os/productions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OsRouteRoute: typeof OsRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  StudioRoute: typeof StudioRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/calendar': {
      id: '/os/calendar'
      path: '/calendar'
      fullPath: '/os/calendar'
      preLoaderRoute: typeof OsCalendarRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/crew': {
      id: '/os/crew'
      path: '/crew'
      fullPath: '/os/crew'
      preLoaderRoute: typeof OsCrewRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/dashboard': {
      id: '/os/dashboard'
      path: '/dashboard'
      fullPath: '/os/dashboard'
      preLoaderRoute: typeof OsDashboardRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/login': {
      id: '/os/login'
      path: '/login'
      fullPath: '/os/login'
      preLoaderRoute: typeof OsLoginRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/clients/': {
      id: '/os/clients/'
      path: '/clients'
      fullPath: '/os/clients/'
      preLoaderRoute: typeof OsClientsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/productions/': {
      id: '/os/productions/'
      path: '/productions'
      fullPath: '/os/productions/'
      preLoaderRoute: typeof OsProductionsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/productions/$id': {
      id: '/os/productions/$id'
      path: '/productions/$id'
      fullPath: '/os/productions/$id'
      preLoaderRoute: typeof OsProductionsIdRouteImport
      parentRoute: typeof OsRouteRoute
    }
  }
}

interface OsRouteRouteChildren {
  OsCalendarRoute: typeof OsCalendarRoute
  OsCrewRoute: typeof OsCrewRoute
  OsDashboardRoute: typeof OsDashboardRoute
  OsLoginRoute: typeof OsLoginRoute
  OsIndexRoute: typeof OsIndexRoute
  OsProductionsIdRoute: typeof OsProductionsIdRoute
  OsClientsIndexRoute: typeof OsClientsIndexRoute
  OsProductionsIndexRoute: typeof OsProductionsIndexRoute
}

const OsRouteRouteChildren: OsRouteRouteChildren = {
  OsCalendarRoute: OsCalendarRoute,
  OsCrewRoute: OsCrewRoute,
  OsDashboardRoute: OsDashboardRoute,
  OsLoginRoute: OsLoginRoute,
  OsIndexRoute: OsIndexRoute,
  OsProductionsIdRoute: OsProductionsIdRoute,
  OsClientsIndexRoute: OsClientsIndexRoute,
  OsProductionsIndexRoute: OsProductionsIndexRoute,
}

const OsRouteRouteWithChildren =
  OsRouteRoute._addFileChildren(OsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OsRouteRoute: OsRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  StudioRoute: StudioRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
